export const SECRETARIA_PRESETS = [
  'Controladoria Geral do Município',
  'IPRES (Instituto de Previdência dos Servidores Municipais de Saquarema)',
  'Procuradoria Geral do Município',
  'Secretaria Municipal da Mulher',
  'Secretaria Municipal de Administração, Receita e Tributação',
  'Secretaria Municipal de Agricultura, Abastecimento e Pesca',
  'Secretaria Municipal de Comunicação Social',
  'Secretaria Municipal de Desenvolvimento Econômico',
  'Secretaria Municipal de Desenvolvimento Social',
  'Secretaria Municipal de Educação, Cultura, Inclusão, Ciência e Tecnologia',
  'Secretaria Municipal de Esporte, Lazer e Turismo',
  'Secretaria Municipal de Finanças',
  'Secretaria Municipal de Gabinete',
  'Secretaria Municipal de Gestão, Inovação e Tecnologia',
  'Secretaria Municipal de Governança e Sustentabilidade',
  'Secretaria Municipal de Habitação',
  'Secretaria Municipal de Infraestrutura',
  'Secretaria Municipal de Meio Ambiente',
  'Secretaria Municipal de Obras Públicas',
  'Secretaria Municipal de Planejamento',
  'Secretaria Municipal de Relações Institucionais',
  'Secretaria Municipal de Saúde',
  'Secretaria Municipal de Segurança e Ordem Pública',
  'Secretaria Municipal de Transparência e Integridade',
  'Secretaria Municipal de Transporte e Serviços Públicos',
  'Secretaria Municipal de Urbanismo',
  'Secretaria Municipal dos Direitos dos Animais',
]
