import {
  Bus,
  Building2,
  ClipboardList,
  Cpu,
  Eye,
  Fish,
  GraduationCap,
  HandCoins,
  Handshake,
  HardHat,
  HeartHandshake,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  type LucideIcon,
  Megaphone,
  PawPrint,
  Scale,
  ShieldAlert,
  ShieldCheck,
  Trees,
  TrendingUp,
  Trophy,
  Wallet,
} from 'lucide-react'

const RULES: [RegExp, LucideIcon][] = [
  [/controladoria/i, ShieldCheck],
  [/previd|ipres/i, HandCoins],
  [/procuradoria/i, Scale],
  [/mulher/i, HeartHandshake],
  [/administra|receita|tributa/i, Landmark],
  [/agricultura|pesca|abastecimento/i, Fish],
  [/comunica/i, Megaphone],
  [/desenvolvimento econ/i, TrendingUp],
  [/desenvolvimento social/i, HeartHandshake],
  [/educa/i, GraduationCap],
  [/esporte|lazer|turismo/i, Trophy],
  [/finan/i, Wallet],
  [/gabinete/i, Building2],
  [/gest|inova|tecnologia/i, Cpu],
  [/governan|sustentabilidade/i, Leaf],
  [/habita(c|ç)(a|ã)o/i, Home],
  [/infraestrutura/i, HardHat],
  [/meio ambiente/i, Trees],
  [/obras/i, HardHat],
  [/planejamento/i, ClipboardList],
  [/rela(c|ç)(o|õ)es institucionais/i, Handshake],
  [/sa(u|ú)de/i, HeartPulse],
  [/seguran(c|ç)a/i, ShieldAlert],
  [/transpar(e|ê)ncia|integridade/i, Eye],
  [/transporte|servi(c|ç)os p(u|ú)blicos/i, Bus],
  [/urbanismo/i, Building2],
  [/animais/i, PawPrint],
]

export function getSecretariaIcon(nome: string): LucideIcon {
  const match = RULES.find(([pattern]) => pattern.test(nome))
  return match ? match[1] : Building2
}
